#include "dsrrl/operators/material_response/mtd_semantic_census.hpp"
#include "dsrrl/operators/material_response/generated_routes_v1.hpp"
#include "dsrrl/operators/material_response/generated_envspec_router_v1.hpp"
#include "dsrrl/operators/material_response/generated_ptde_flver_texture_semantics_v1.hpp"
#include "dsrrl/operators/material_response/generated_flver_pairwise_semantics_v1.hpp"
#include <cstddef>
namespace dsrrl::operators::material_response { namespace {
constexpr std::uint32_t op_bit(mtd_semantic_operator op) noexcept { return 1u<<static_cast<std::uint8_t>(op); }
constexpr std::uint32_t k_full24_use_mask=op_bit(mtd_semantic_operator::material_response)|op_bit(mtd_semantic_operator::spec_rgb)|op_bit(mtd_semantic_operator::hemenv)|op_bit(mtd_semantic_operator::texture_resource_consumers);
constexpr std::uint32_t k_full24_no_use_mask=op_bit(mtd_semantic_operator::pointlight);
struct override_seed{const char*name;const char*sha256;std::uint32_t receiver0,receiver1,receiver2,use_mask,no_use_mask;};
inline constexpr override_seed k_overrides[]={{"Ps_Body[DSB].mtd","af2f108831b783a43b0e02f047919719d14f38e68d6c5a97b80678d593ba1c95",33u,34u,35u,0u,op_bit(mtd_semantic_operator::subsurface)},{"P_Metal[DSB].mtd","ece70f36bd2517d28c8495e276cea537f8b519d6bed981788e79a409ffbf763b",33u,34u,35u,op_bit(mtd_semantic_operator::env_spec),0u}};
struct exact_binding_seed{const char*name;const char*sha256;const char*material_family;std::uint32_t receiver0,receiver1,receiver2;mtd_gate_policy gate_policy;};
inline constexpr exact_binding_seed k_exact_bindings[]={{"P_Metal[DSB]_Spec.mtd","c8504bfa64c84d5035bc56ab63e43d319ef69af08c5044e0260b639ab1b78ffc","DifSpcBmp",33u,34u,35u,mtd_gate_policy::direct_exact},{"P_DullLeather[DSB]_Edge_Spec.mtd","9d24347d2bfa90df062f39a281fd0ae07f160203f1dc8c5d114ac218a6daa4c2","DifSpcBmp",33u,34u,35u,mtd_gate_policy::direct_exact},{"P_DullLeather[DSB]_Spec.mtd","4def97828f95a75b64641fa9f64ba1fc58e909e69479c0d4460aaaf9cd466ee5","DifSpcBmp",33u,34u,35u,mtd_gate_policy::direct_exact},{"P_Leather[DSB]_Alp_Spec.mtd","deeb55a8e4d50767aeaba98ba9bfa97b0fb404f901249f5ca13fa762610debda","DifSpcBmp",33u,34u,35u,mtd_gate_policy::direct_exact},{"P_Leather[DS].mtd","53819ead337c1ecd8593d8535c1fc1fdde589f00eb8ea015a8ae347da71073ea","DifSpcBmp",33u,34u,35u,mtd_gate_policy::direct_exact},{"P_Leather[DSB].mtd","0f2b9a1012b83c4dfc909c311d29a11147de8c15191bc62398ce0d5e1cc6757e","DifSpcBmp",33u,34u,35u,mtd_gate_policy::ptde_companion_required},{"C_DullLeather[DSB].mtd","613a3296e7906b2dea5c0cd48bda37c8628b850bad9988688a40595c4c49eaad","DifSpcBmp",33u,34u,35u,mtd_gate_policy::ptde_companion_required},{"C_Wet[DSB].mtd","d3885a4c00b844cdb1a09b571cb037343e5bad31249e7ec80ed5e7da195b9e6f","DifSpcBmp",33u,34u,35u,mtd_gate_policy::ptde_companion_required}};
constexpr std::uint32_t k_exact_binding_use_mask=op_bit(mtd_semantic_operator::material_response)|op_bit(mtd_semantic_operator::hemenv);constexpr std::uint32_t k_exact_binding_no_use_mask=op_bit(mtd_semantic_operator::pointlight);
int hex_value(char c) noexcept{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return 10+c-'a';if(c>='A'&&c<='F')return 10+c-'A';return -1;}bool digest_matches_hex(const core::sha256_digest&d,const char*h) noexcept{if(!h)return false;for(std::size_t i=0;i<d.size();++i){int hi=hex_value(h[i*2]),lo=hex_value(h[i*2+1]);if(hi<0||lo<0||d[i]!=static_cast<std::uint8_t>((hi<<4)|lo))return false;}return h[64]=='\0';}bool receiver_matches(std::uint32_t r,std::uint32_t a,std::uint32_t b,std::uint32_t c) noexcept{return r==a||r==b||r==c;}mtd_semantic_state state_from_masks(mtd_semantic_operator op,std::uint32_t u,std::uint32_t n) noexcept{auto b=op_bit(op);if(u&b)return mtd_semantic_state::use;if(n&b)return mtd_semantic_state::no_use;return mtd_semantic_state::unknown;}bool exact_identity(const material_identity&i,const char*n,const char*s) noexcept{return i.valid&&i.semantic_name_hash&&i.semantic_name_hash==mtd_semantic_hash(n)&&digest_matches_hex(i.raw_mtd_sha256,s);}
mtd_envspec_semantics envspec_from_router_record(const generated::envspec_router_record&s) noexcept{mtd_envspec_semantics o;o.exact_identity_match=true;o.envspc_slot_valid=s.envspc_slot<4u;o.envspc_slot=s.envspc_slot;o.suppress_dsr_only_safe=s.explicit_none_safe;switch(s.state){case generated::envspec_router_state::present:o.presence=ptde_envspec_presence::present;o.router_state=mtd_envspec_router_state::present;break;case generated::envspec_router_state::explicit_none:o.presence=ptde_envspec_presence::absent;o.router_state=mtd_envspec_router_state::explicit_none;break;case generated::envspec_router_state::nospc_host:o.presence=ptde_envspec_presence::absent;o.router_state=mtd_envspec_router_state::nospc_host;o.suppress_dsr_only_safe=false;break;default:o.presence=ptde_envspec_presence::unknown;o.router_state=mtd_envspec_router_state::unknown;o.suppress_dsr_only_safe=false;}return o;}bool envspec_router_semantics_equal(const generated::envspec_router_record&a,const generated::envspec_router_record&b) noexcept{return a.state==b.state&&a.envspc_slot==b.envspc_slot&&a.explicit_none_safe==b.explicit_none_safe;}
const generated::ptde_flver_texture_semantic_record *find_ptde_texture_by_name_hash(std::uint64_t h) noexcept{if(!h)return nullptr;for(const auto&s:generated::k_ptde_flver_texture_semantics_v1)if(s.semantic_name_hash==h)return &s;return nullptr;}
const generated::ptde_flver_texture_semantic_record *find_ptde_texture_by_legacy_hash(std::uint64_t h) noexcept{if(!h)return nullptr;for(const auto&s:generated::k_ptde_flver_texture_semantics_v1)if(s.legacy_name_hash_utf16_lower==h)return &s;return nullptr;}
bool exact_host_identity_for_texture(const material_identity&i,const generated::ptde_flver_texture_semantic_record&s) noexcept{if(!i.valid||!i.semantic_name_hash||i.semantic_name_hash!=s.semantic_name_hash)return false;for(const auto&host:generated::k_envspec_router_v1)if(host.semantic_name_hash==s.semantic_name_hash&&host.raw_mtd_sha256==i.raw_mtd_sha256)return true;return false;}
bool exact_host_identity_for_texture_legacy(std::uint64_t h,const core::sha256_digest&sha,const generated::ptde_flver_texture_semantic_record&s) noexcept{if(!h||h!=s.legacy_name_hash_utf16_lower)return false;for(const auto&host:generated::k_envspec_router_v1)if(host.legacy_name_hash_utf16_lower==h&&host.raw_mtd_sha256==sha)return true;return false;}
}
std::uint64_t mtd_semantic_hash(const char*t) noexcept{constexpr std::uint64_t o=14695981039346656037ull,p=1099511628211ull;if(!t)return 0;std::uint64_t h=o;for(;*t;++t){h^=static_cast<std::uint8_t>(*t);h*=p;}return h;}
bool has_exact_flver_material_ownership(const mtd_semantic_query&q) noexcept{return q.ownership.exact&&q.ownership.flver_identity_hash!=0u&&q.ownership.material_slot_valid;}
// Only semantics whose newly recovered evidence is explicitly resource/slot scoped
// are gated here. Existing independently certified exact-MTD routes (EnvSpec,
// Subsurface, SpecRGB) retain their current gates until their FLVER row payload is
// reproducibly imported; this avoids turning a construction discovery into a
// runtime regression.
bool operator_requires_flver_material_ownership(mtd_semantic_operator op) noexcept{return op==mtd_semantic_operator::diffuse||op==mtd_semantic_operator::normal_bump;}
mtd_envspec_semantics classify_mtd_envspec_semantics(const mtd_semantic_query&q) noexcept{mtd_envspec_semantics o;if(!q.material.valid||!q.material.semantic_name_hash)return o;for(const auto&s:generated::k_envspec_router_v1)if(q.material.semantic_name_hash==s.semantic_name_hash&&q.material.raw_mtd_sha256==s.raw_mtd_sha256)return envspec_from_router_record(s);return o;}
mtd_envspec_semantics classify_mtd_envspec_semantics_legacy(std::uint64_t h,const core::sha256_digest&sha) noexcept{mtd_envspec_semantics o;const generated::envspec_router_record*c=nullptr;for(const auto&s:generated::k_envspec_router_v1){if(s.raw_mtd_sha256!=sha)continue;if(s.legacy_name_hash_utf16_lower==h)return envspec_from_router_record(s);if(c==nullptr)c=&s;else if(!envspec_router_semantics_equal(*c,s))return o;}return c?envspec_from_router_record(*c):o;}
ptde_flver_texture_semantics classify_ptde_flver_texture_semantics(const material_identity&m) noexcept{ptde_flver_texture_semantics o;const auto*s=find_ptde_texture_by_name_hash(m.semantic_name_hash);if(!s||!exact_host_identity_for_texture(m,*s))return o;o.positive_mask=s->positive_mask;o.exact_host_identity_match=true;o.source_complete=generated::k_ptde_flver_texture_semantics_source_complete;return o;}
ptde_flver_texture_semantics classify_ptde_flver_texture_semantics_legacy(std::uint64_t h,const core::sha256_digest&sha) noexcept{ptde_flver_texture_semantics o;if(const auto*s=find_ptde_texture_by_legacy_hash(h);s&&exact_host_identity_for_texture_legacy(h,sha,*s)){o.positive_mask=s->positive_mask;o.exact_host_identity_match=true;o.source_complete=generated::k_ptde_flver_texture_semantics_source_complete;return o;}const generated::ptde_flver_texture_semantic_record*c=nullptr;for(const auto&host:generated::k_envspec_router_v1){if(host.raw_mtd_sha256!=sha)continue;const auto*cap=find_ptde_texture_by_legacy_hash(host.legacy_name_hash_utf16_lower);if(!cap)return {};if(c==nullptr)c=cap;else if(c->positive_mask!=cap->positive_mask)return {};}if(c){o.positive_mask=c->positive_mask;o.exact_host_identity_match=true;o.source_complete=generated::k_ptde_flver_texture_semantics_source_complete;}return o;}
bool ptde_flver_texture_semantic_present(const ptde_flver_texture_semantics&s,ptde_texture_semantic semantic) noexcept{const auto bit=static_cast<std::uint8_t>(1u<<static_cast<std::uint8_t>(semantic));return s.exact_host_identity_match&&(s.positive_mask&bit)!=0u;}
mtd_semantic_decision classify_mtd_semantic(const mtd_semantic_query&q,mtd_semantic_operator op) noexcept{if(!q.material.valid||!q.receiver_id)return {};if(operator_requires_flver_material_ownership(op)&&!has_exact_flver_material_ownership(q))return {};if(op==mtd_semantic_operator::diffuse||op==mtd_semantic_operator::normal_bump){const auto tex=classify_ptde_flver_texture_semantics(q.material);const auto sem=op==mtd_semantic_operator::diffuse?ptde_texture_semantic::diffuse:ptde_texture_semantic::bump;if(ptde_flver_texture_semantic_present(tex,sem)){const bool pairwise_stable=op==mtd_semantic_operator::diffuse?generated::flver_pairwise_diffuse_stable_after_ptde_positive(q.material.semantic_name_hash):generated::flver_pairwise_bump_stable_after_ptde_positive(q.material.semantic_name_hash);if(pairwise_stable)return{mtd_semantic_state::use,mtd_semantic_source::flver_pairwise_stable_exact,mtd_gate_policy::exact_material,true};}}if(op==mtd_semantic_operator::env_spec){auto e=classify_mtd_envspec_semantics(q);if(e.exact_identity_match){auto st=e.presence==ptde_envspec_presence::present?mtd_semantic_state::use:e.presence==ptde_envspec_presence::absent?mtd_semantic_state::no_use:mtd_semantic_state::unknown;return{st,mtd_semantic_source::envspec_router_exact,mtd_gate_policy::exact_material,true};}}for(const auto&s:k_overrides){if(!receiver_matches(q.receiver_id,s.receiver0,s.receiver1,s.receiver2)||!exact_identity(q.material,s.name,s.sha256))continue;auto st=state_from_masks(op,s.use_mask,s.no_use_mask);if(st!=mtd_semantic_state::unknown)return{st,mtd_semantic_source::exact_override,mtd_gate_policy::exact_material,true};break;}for(const auto&s:k_exact_bindings){if(!receiver_matches(q.receiver_id,s.receiver0,s.receiver1,s.receiver2)||!exact_identity(q.material,s.name,s.sha256)||!q.material.material_family_hash||q.material.material_family_hash!=mtd_semantic_hash(s.material_family))continue;return{state_from_masks(op,k_exact_binding_use_mask,k_exact_binding_no_use_mask),mtd_semantic_source::exact_binding_extension,s.gate_policy,true};}for(const auto&s:generated::k_material_routes_v1){if(q.material.route_index!=s.route_index||!q.material.semantic_name_hash||q.material.semantic_name_hash!=mtd_semantic_hash(s.mtd_name)||!digest_matches_hex(q.material.raw_mtd_sha256,s.sha256)||!q.material.material_family_hash||q.material.material_family_hash!=mtd_semantic_hash(s.material_family)||!receiver_matches(q.receiver_id,s.receiver0,s.receiver1,s.receiver2))continue;return{state_from_masks(op,k_full24_use_mask,k_full24_no_use_mask),mtd_semantic_source::full24_exact_cohort,mtd_gate_policy::exact_material,true};}return {};}
ptde_envspec_presence mtd_envspec_presence(const mtd_semantic_query&q) noexcept{auto e=classify_mtd_envspec_semantics(q);if(e.exact_identity_match)return e.presence;auto r=classify_mtd_semantic(q,mtd_semantic_operator::env_spec);if(r.state==mtd_semantic_state::use)return ptde_envspec_presence::present;if(r.state==mtd_semantic_state::no_use)return ptde_envspec_presence::absent;return ptde_envspec_presence::unknown;}
} // namespace dsrrl::operators::material_response