#include "dsrrl/core/operator_catalog.hpp"
#include "dsrrl/operators/surface/faceeye_shadow.hpp"
#include "dsrrl/operators/point_light/legacy_specular.hpp"
#include "dsrrl/operators/point_light/runtime_readiness.hpp"
#include <cmath>
#include <iostream>
using namespace dsrrl;
namespace {
bool check(bool c,const char*e,int l){if(c)return true;std::cerr<<"CHECK FAILED line "<<l<<": "<<e<<'\n';return false;}
#define CHECK(e) do{if(!check(static_cast<bool>(e),#e,__LINE__))return 1;}while(false)
core::activation_context activation(){core::activation_context c;c.receiver_verified=c.material_verified=c.resource_ready=c.producer_ready=c.consumer_verified=c.immediate_context=c.graph_ready=true;return c;}
operators::surface::faceeye_auxiliary_snapshot_descriptor faceeye_aux_ready(bool csd){using namespace operators::surface;faceeye_auxiliary_snapshot_descriptor s;s.register_present.fill(true);s.producer_offsets=k_faceeye_aux_dirlight_offsets;s.immutable_draw_local=true;s.value_homology_verified[0]=true;s.value_homology_verified[1]=true;s.value_homology_verified[24]=true;if(csd)for(std::size_t i=2;i<=22;++i)s.value_homology_verified[i]=true;return s;}
operators::surface::faceeye_runtime_context faceeye_ready(operators::surface::faceeye_receiver_variant v){using namespace operators::surface;const bool csd=v==faceeye_receiver_variant::csd_no_point||v==faceeye_receiver_variant::csd_pnts||v==faceeye_receiver_variant::csd_pntss||v==faceeye_receiver_variant::csd_pntssss;faceeye_runtime_context c;c.receiver_verified=true;c.variant=v;c.replacement_ptde_kernel_shader_ready=true;c.stock_ptde_kernel_identity_verified=true;c.runtime_t7_identity_verified=true;c.auxiliary_dirlight_snapshot_ready=true;c.auxiliary_dirlight_snapshot=faceeye_aux_ready(csd);c.csd_matrix_region_ready=true;c.stock_regular_s7_verified=true;c.regular_s7_sampler_ready=true;c.regular_s7_descriptor_verified=true;c.sampler_override_transaction_ready=true;c.legacy_env_probe_routes_ready=true;c.independent_lighting_exclusion_verified=true;c.draw_transaction_ready=true;return c;}
operators::point_light::local_specular_runtime_context local_ready(operators::point_light::local_specular_receiver_class cls){using namespace operators::point_light;local_specular_runtime_context c;c.receiver_verified=true;c.receiver_class=cls;c.material_c101_c102_verified=true;c.spec_rgb_route_ready=true;c.source_amplitude_category_ready=true;c.attenuation_ready=true;c.fixed_membership_verified=true;c.clustered_membership_sidecar_ready=true;c.clustered_four_slot_shader_ready=true;c.stock_cluster_membership_bypassed=true;c.complete_microfacet_window_owned=true;c.stock_roughness_tail_bypassed=true;c.stock_common_ndotl_specular_bypassed=true;c.diffuse_path_preserved=true;c.separate_specular_output_cut_ready=true;c.draw_transaction_ready=true;return c;}
operators::point_light::pointlight_runtime_context point_ready(operators::point_light::pointlight_receiver_stratum s){using namespace operators::point_light;pointlight_runtime_context c;c.receiver_verified=true;c.receiver_stratum=s;c.source_scope_verified=true;c.source_scope=pointlight_source_scope::ordinary_map_or_dynamic;c.source_instance_state_ready=true;c.source_amplitude_category_ready=true;c.attenuation_ready=true;c.fixed_receiver_payload_ready=true;c.fixed_membership_verified=true;c.clustered_cpu_membership_sidecar_ready=true;c.clustered_membership_order_verified=true;c.clustered_count_provenance_ready=true;c.clustered_raw_selected_count=4;c.clustered_material_max_count=4;c.clustered_effective_count=4;c.clustered_four_slot_shader_ready=true;c.stock_cluster_membership_bypassed=true;c.diffuse_material_path_ready=true;c.local_specular_path_ready=true;c.terminal_sat_ready=true;c.downstream_atmosphere_ready=true;c.draw_transaction_ready=true;return c;}
}
int main(){using namespace operators::surface;auto aux=faceeye_aux_ready(false);CHECK(validate_faceeye_auxiliary_snapshot(aux,false));CHECK(!validate_faceeye_auxiliary_snapshot(aux,true));aux.register_present[0]=false;CHECK(!validate_faceeye_auxiliary_snapshot(aux,false));aux=faceeye_aux_ready(false);aux.producer_offsets[25]=0x390;CHECK(!validate_faceeye_auxiliary_snapshot(aux,false));aux=faceeye_aux_ready(false);aux.value_homology_verified[24]=false;CHECK(!validate_faceeye_auxiliary_snapshot(aux,false));
 core::feature_registry ff;const auto a=activation();CHECK(ff.set(core::operator_id::faceeye_shadow_legacy,true));auto fc=faceeye_ready(faceeye_receiver_variant::sdw_no_point);auto fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(fp.ready);CHECK(fp.replace_comparison_kernel);CHECK(!fp.use_stock_ptde_style_kernel);CHECK(fp.override_s7_with_regular_sampler);fc.auxiliary_dirlight_snapshot.value_homology_verified[24]=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::auxiliary_value_homology_incomplete);fc=faceeye_ready(faceeye_receiver_variant::sdw_no_point);fc.replacement_ptde_kernel_shader_ready=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::replacement_ptde_kernel_shader_not_ready);
 fc=faceeye_ready(faceeye_receiver_variant::sdw_pntss);fc.regular_s7_sampler_ready=false;fc.regular_s7_descriptor_verified=false;fc.sampler_override_transaction_ready=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(fp.ready);CHECK(!fp.replace_comparison_kernel);CHECK(fp.use_stock_ptde_style_kernel);CHECK(!fp.override_s7_with_regular_sampler);fc.stock_ptde_kernel_identity_verified=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::stock_ptde_kernel_identity_not_verified);
 fc=faceeye_ready(faceeye_receiver_variant::csd_pntssss);fc.auxiliary_dirlight_snapshot.value_homology_verified[10]=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::auxiliary_value_homology_incomplete);fc=faceeye_ready(faceeye_receiver_variant::csd_pntssss);fc.csd_matrix_region_ready=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::csd_matrix_region_not_ready);fc=faceeye_ready(faceeye_receiver_variant::sdw_no_point);fc.auxiliary_dirlight_snapshot.register_present[4]=false;fp=evaluate_faceeye_runtime_readiness(ff,a,fc);CHECK(!fp.ready);CHECK(fp.reason==faceeye_runtime_reason::auxiliary_dirlight_snapshot_incomplete);
 const auto ls=core::find_operator_contract(core::operator_id::local_specular_legacy);CHECK(ls.has_value());CHECK(ls->status==core::canonical_status::confirmed);core::feature_registry f;CHECK(f.set(core::operator_id::local_specular_legacy,true));operators::point_light::legacy_specular_vector_input v{};v.source_rgb={1,2,3};v.attenuation=.5f;v.normal={0,1,0};v.view_direction={0,1,0};v.light_direction={0,1,0};v.exponent_c102=2;v.spec_texture_blend={.5f,1,2};v.c101=2;v.color0={1,.5f,.25f};auto s=operators::point_light::evaluate_legacy_local_specular(v);CHECK(s.result==operators::point_light::legacy_specular_math_result::exact);CHECK(std::fabs(s.reflection.y-1)<1e-6f);CHECK(std::fabs(s.r_dot_l-1)<1e-6f);v.normal={0,2,0};s=operators::point_light::evaluate_legacy_local_specular(v);CHECK(s.result==operators::point_light::legacy_specular_math_result::fail_open_invalid_vector);
 auto c=local_ready(operators::point_light::local_specular_receiver_class::fixed_spc_pntss);auto p=operators::point_light::evaluate_local_specular_runtime_readiness(f,a,c);CHECK(p.ready);CHECK(p.bypass_dsr_microfacet);c.complete_microfacet_window_owned=false;p=operators::point_light::evaluate_local_specular_runtime_readiness(f,a,c);CHECK(!p.ready);c=local_ready(operators::point_light::local_specular_receiver_class::clustered_pnts);c.clustered_membership_sidecar_ready=false;p=operators::point_light::evaluate_local_specular_runtime_readiness(f,a,c);CHECK(!p.ready);CHECK(f.set(core::operator_id::point_light,true));auto pc=point_ready(operators::point_light::pointlight_receiver_stratum::clustered_pnts);pc.clustered_material_max_count=2;pc.clustered_effective_count=2;auto pp=operators::point_light::evaluate_pointlight_runtime_readiness(f,a,pc);CHECK(pp.ready);CHECK(pp.selected_light_count==2);std::cout<<"faceeye_pointlight_readiness_tests: PASS\n";return 0;}
