#include "dsrrl/core/operator_catalog.hpp"
#include "dsrrl/operators/resource_bridges/subsurface_runtime_readiness.hpp"
#include "dsrrl/operators/resource_bridges/envdiffuse_runtime_readiness.hpp"
#include "dsrrl/operators/lightbank/hemdir3.hpp"
#include "dsrrl/operators/env_spec/legacy_runtime_readiness.hpp"

#include <array>
#include <cmath>
#include <iostream>
#include <limits>

using namespace dsrrl;
namespace {
bool check(bool c,const char*e,int l){if(c)return true;std::cerr<<"CHECK FAILED line "<<l<<": "<<e<<'\n';return false;}
#define CHECK(e) do{if(!check(static_cast<bool>(e),#e,__LINE__))return 1;}while(false)
core::activation_context verified_activation(){core::activation_context c;c.receiver_verified=c.material_verified=c.resource_ready=c.producer_ready=c.consumer_verified=c.immediate_context=c.graph_ready=true;return c;}
operators::resource_bridges::subsurface_runtime_context ready_subsurface(){using namespace operators::resource_bridges;subsurface_runtime_context c;c.route.actual_material_verified=true;c.route.actual_material_name=k_dsr_body_subsurf_material;c.route.actual_material_sha256=k_dsr_body_subsurf_material_sha256;c.route.actual_receiver_verified=true;c.route.actual_receiver_name=k_subsurface_receiver_routes[0].dsr_receiver_name;c.route.actual_receiver_sha256=k_subsurface_receiver_routes[0].dsr_receiver_sha256;c.route.actual_body_texture_verified=true;c.route.body_spec_texture=subsurface_body_texture::bd_f_body_s;c.route.stable_hemenv_no_pointlight_draw_verified=true;c.route.ptde_slot_mapping_verified=true;c.route.ptde_donor_verified=true;c.route.ptde_material_name=k_ptde_body_plain_material;c.route.ptde_material_sha256=k_ptde_body_plain_material_sha256;c.route.ptde_subsurface_usage_verified=true;c.route.ptde_uses_subsurface=false;c.route.ptde_plain_surface_target_verified=true;c.route.target_plain_receiver_ready=true;c.route.spec_rgb_route_ready=true;c.route.diffuse_route_ready=true;c.route.normal_route_ready=true;c.route.material_response_route_ready=true;c.route.dsr_subsurf_bypass_carrier_ready=true;c.replacement_shader_materialized=true;c.replacement_shader_identity_verified=true;c.replacement_shader_lifecycle_verified=true;return c;}
operators::resource_bridges::envdiffuse_runtime_context ready_envdiffuse(){using namespace operators::resource_bridges;envdiffuse_runtime_context c;c.producer_snapshot_ready=true;c.endpoint_inverse_verified=true;c.alpha_beta_preserved=true;c.draw_multiplier_preserved=true;c.envspec_lanes_preserved=true;c.receiver_verified=true;c.receiver_family=envdiffuse_receiver_family::heme_env_lerp;c.exact_probe_assignment_verified=true;c.probe_a_srv_ready=true;c.probe_b_srv_ready=true;c.sampler_s11_verified=true;c.sampler_s13_verified=true;c.resource_ownership_ready=true;c.draw_restore_ready=true;return c;}
operators::lightbank::hemdir3_runtime_context ready_hemdir3(){using namespace operators::lightbank;hemdir3_runtime_context c;c.semantic.mode=2;c.semantic.domain=hemdir3_semantic_domain::lighting_family_selector;c.semantic.provenance=hemdir3_semantic_provenance::independently_verified_special_route;c.semantic.immutable_draw_local=true;c.semantic.exact_owner_context=true;c.semantic.lightbank_tuple_fresh=true;c.semantic.effective_mode_observation_verified=true;c.upper_lower_source_ready=true;c.d123_source_ready=true;c.b13_carrier_ready=true;c.receiver_verified=true;c.host_envdiffuse_source_suppressed=true;c.material_continuation_ready=true;c.downstream_material_domain_ready=true;c.downstream_postfog_ready=true;c.atmosphere_route_verified=true;c.draw_transaction_ready=true;return c;}
operators::env_spec::legacy_runtime_context ready_packed_envspec(){using namespace operators::env_spec;legacy_runtime_context c;c.resource_class=legacy_resource_class::packed_gi;c.receiver_verified=true;c.material_verified=true;c.ptde_receiver_math_ready=true;c.dsr_pbl_bypass_ready=true;c.material_response_b12_ready=true;c.sampler_descriptor_verified=true;c.semantic_sidecar_lookup_ready=true;c.packed_gi_resource_ready=true;c.packed_gi_stored_alpha_preserved=true;c.draw_transaction_ready=true;return c;}
}
int main(){
 const auto subsurface_contract=core::find_operator_contract(core::operator_id::subsurface);CHECK(subsurface_contract.has_value());CHECK(subsurface_contract->default_state==core::port_state::active_candidate);
 const auto envdiffuse_contract=core::find_operator_contract(core::operator_id::env_diffuse);CHECK(envdiffuse_contract.has_value());CHECK(envdiffuse_contract->default_state==core::port_state::partial);
 const auto hemdir3_contract=core::find_operator_contract(core::operator_id::hemdir3);CHECK(hemdir3_contract.has_value());CHECK(hemdir3_contract->default_state==core::port_state::partial);
 const auto envspec_contract=core::find_operator_contract(core::operator_id::env_spec);CHECK(envspec_contract.has_value());CHECK(envspec_contract->default_state==core::port_state::partial);
 auto activation=verified_activation();core::feature_registry features;
 CHECK(features.set(core::operator_id::subsurface,true));auto subsurface=ready_subsurface();auto subsurface_plan=operators::resource_bridges::evaluate_subsurface_runtime_readiness(features,activation,subsurface);CHECK(subsurface_plan.ready);CHECK(subsurface_plan.route.target_plain_receiver_id==33u);
 subsurface.replacement_shader_lifecycle_verified=false;subsurface_plan=operators::resource_bridges::evaluate_subsurface_runtime_readiness(features,activation,subsurface);CHECK(!subsurface_plan.ready);CHECK(subsurface_plan.reason==operators::resource_bridges::subsurface_runtime_reason::replacement_shader_lifecycle_not_verified);
 subsurface=ready_subsurface();subsurface.route.spec_rgb_route_ready=false;subsurface_plan=operators::resource_bridges::evaluate_subsurface_runtime_readiness(features,activation,subsurface);CHECK(!subsurface_plan.ready);
 CHECK(features.set(core::operator_id::env_diffuse,true));auto envdiffuse=ready_envdiffuse();auto envdiffuse_plan=operators::resource_bridges::evaluate_envdiffuse_runtime_readiness(features,activation,envdiffuse);CHECK(envdiffuse_plan.ready);envdiffuse.exact_probe_assignment_verified=false;envdiffuse_plan=operators::resource_bridges::evaluate_envdiffuse_runtime_readiness(features,activation,envdiffuse);CHECK(!envdiffuse_plan.ready);
 using operators::lightbank::hemdir3_lobe;using operators::lightbank::hemdir3_vec3;const hemdir3_vec3 H{.1f,.2f,.3f},N{0,1,0};const std::array<hemdir3_lobe,3> lobes{{{{0,-1,0},{1,0,0}},{{0,1,0},{0,1,0}},{{1,0,0},{0,0,1}}}};auto h=operators::lightbank::evaluate_hemdir3_source_join(H,N,lobes);CHECK(h.result==operators::lightbank::hemdir3_math_result::exact);CHECK(std::fabs(h.joined_source.x-1.1f)<.000001f);
 CHECK(features.set(core::operator_id::hemdir3,true));auto hemdir3=ready_hemdir3();auto hemdir3_plan=operators::lightbank::evaluate_hemdir3_runtime_readiness(features,activation,hemdir3);CHECK(hemdir3_plan.ready);CHECK(hemdir3_plan.suppress_host_envdiffuse);
 hemdir3.semantic.domain=operators::lightbank::hemdir3_semantic_domain::model_packed_enable_helper;hemdir3_plan=operators::lightbank::evaluate_hemdir3_runtime_readiness(features,activation,hemdir3);CHECK(!hemdir3_plan.ready);CHECK(hemdir3_plan.reason==operators::lightbank::hemdir3_runtime_reason::semantic_domain_not_lighting_selector);
 hemdir3=ready_hemdir3();hemdir3.semantic.provenance=operators::lightbank::hemdir3_semantic_provenance::synthetic_debug_override;hemdir3_plan=operators::lightbank::evaluate_hemdir3_runtime_readiness(features,activation,hemdir3);CHECK(!hemdir3_plan.ready);CHECK(hemdir3_plan.reason==operators::lightbank::hemdir3_runtime_reason::semantic_snapshot_not_proven);
 hemdir3=ready_hemdir3();hemdir3.semantic.effective_mode_observation_verified=false;hemdir3_plan=operators::lightbank::evaluate_hemdir3_runtime_readiness(features,activation,hemdir3);CHECK(!hemdir3_plan.ready);CHECK(hemdir3_plan.reason==operators::lightbank::hemdir3_runtime_reason::semantic_snapshot_not_proven);
 CHECK(features.set(core::operator_id::env_spec,true));auto envspec=ready_packed_envspec();auto envspec_plan=operators::env_spec::evaluate_legacy_runtime_readiness(features,activation,envspec);CHECK(envspec_plan.ready);envspec.resource_class=operators::env_spec::legacy_resource_class::classic_rgb24;envspec.packed_gi_resource_ready=false;envspec.packed_gi_stored_alpha_preserved=false;envspec.classic_resource_ready=true;envspec.classic_api_alpha_one=true;envspec.classic_selector_algorithm_verified=true;envspec.classic_authored_selector_values_verified=false;envspec_plan=operators::env_spec::evaluate_legacy_runtime_readiness(features,activation,envspec);CHECK(!envspec_plan.ready);
 core::feature_registry disabled;subsurface=ready_subsurface();subsurface_plan=operators::resource_bridges::evaluate_subsurface_runtime_readiness(disabled,activation,subsurface);CHECK(!subsurface_plan.ready);
 std::cout<<"future_runtime_readiness_tests: PASS\n";return 0;
}
