#include "dsrrl/core/operator_catalog.hpp"
#include "dsrrl/core/island_policy.hpp"
#include "dsrrl/operators/postprocess/future_runtime_preflight.hpp"
#include "dsrrl/operators/postprocess/bloom_legacy_graph.hpp"
#include "dsrrl/operators/postprocess/bloom_scene_bridge.hpp"
#include <iostream>
using namespace dsrrl;
namespace { bool check(bool c,const char*e,int l){if(c)return true;std::cerr<<"CHECK FAILED line "<<l<<": "<<e<<'\n';return false;} }
#define CHECK(e) do{if(!check(static_cast<bool>(e),#e,__LINE__))return 1;}while(false)
int main(){using namespace operators::postprocess;
 const auto bc=core::find_operator_contract(core::operator_id::post_bloom);CHECK(bc.has_value());CHECK(bc->status==core::canonical_status::confirmed);CHECK(bc->default_state==core::port_state::blocked);
 core::feature_registry f;CHECK(f.set(core::operator_id::post_bloom,true));core::activation_context a;a.receiver_verified=true;a.material_verified=true;a.resource_ready=true;a.producer_ready=true;a.consumer_verified=true;a.immediate_context=true;a.graph_ready=true;auto g=core::evaluate_operator_activation(f,core::operator_id::post_bloom,a);CHECK(g.state==core::island_state::fail_open);
 bloom_scene_bridge_carrier s;s.source_domain=bloom_scene_source_domain::ptde_normalized_scene_history_q8;s.history_proof=bloom_scene_history_proof::writer_set_closed;s.strategy=bloom_scene_construction_strategy::late_fullscreen_reconstruction;s.proven_writer_classes=bloom_known_writer_classes;s.writer_set_exhaustiveness_proven=true;s.writer_order=bloom_writer_order_proof::execution_order_closed;s.draw_recurrence=bloom_draw_recurrence_proof::target_write_recurrence_closed;s.fx_sfx_recurrence=bloom_fx_sfx_recurrence_proof::target_write_recurrence_closed;s.fx_material_route=bloom_fx_material_route_proof::collector_material_binding_closed;s.fx_blend_semantics=bloom_fx_blend_semantics_proof::render_state_tuple_closed;s.q8_a8r8g8b8_storage_verified=true;s.source_freshness_verified=true;s.draw_local_handoff_verified=true;
 CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::fx_identity_join_not_closed);s.fx_identity_join=bloom_fx_identity_join_proof::same_authored_material_closed;CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::fx_identity_join_not_closed);s.fx_identity_join=bloom_fx_identity_join_proof::same_runtime_material_instance_closed;CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::fx_identity_join_not_closed);s.fx_identity_join=bloom_fx_identity_join_proof::same_collector_draw_closed;CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::blend_history_not_closed);
 s.history_proof=bloom_scene_history_proof::blend_history_closed;CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::late_fullscreen_reconstruction_rejected);s.strategy=bloom_scene_construction_strategy::pre_storage_history_replay;CHECK(validate_bloom_scene_bridge_carrier(s)==bloom_scene_bridge_result::exact_construction);
 bloom_legacy_graph_carrier q;q.q8_scene_1024x720_ready=true;q.packed_depth_256x180_ready=true;q.fixed_rgba_256x180_ready=true;q.fixed_rgba_128x90_ready=true;q.first_pass04=bloom_pass04_role::packed_depth_first;q.second_pass04=bloom_pass04_role::pre_brightpass_color_copy_second;q.second_pass04_source_is_q8_scene=true;q.second_pass04_destination_is_rgba_256x180=true;q.pass18_brightpass_ready=true;q.pass19_blur_h_ready=true;q.pass1a_blur_v_ready=true;q.hdr_t1_consumes_rgba_128x90=true;CHECK(validate_bloom_legacy_graph_carrier(q)==bloom_legacy_graph_result::exact_construction);
 std::cout<<"postprocess_unblock_tests: PASS\n";return 0;
}
