#include "dsrrl/runtime/spec_rgb_resource_cache.hpp"
#include <iostream>
using namespace dsrrl;
namespace {
bool check(bool c,const char *e,int l){if(c)return true;std::cerr<<"CHECK FAILED line "<<l<<": "<<e<<'\n';return false;}
#define CHECK(e) do { if(!check(static_cast<bool>(e),#e,__LINE__)) return 1; } while(false)
runtime::spec_rgb_bind_request ready_request(){runtime::spec_rgb_bind_request r;r.route.receiver_id=33;r.route.actual_material_verified=true;r.route.material_specular_consumer_verified=true;r.route.exact_name_ptde_companion_verified=true;r.route.ptde_sidecar_ready=true;r.route.native_t10_transport_ready=true;r.route.stock_t1_preserved=true;r.logical_name=u"chr/c0000/tex/body_s";r.currently_bound_t1=0x101u;return r;}
}
int main(){runtime::spec_rgb_resource_cache cache;CHECK(cache.register_exact(u"",0x101u,0x201u)==runtime::spec_rgb_resource_result::fail_open_invalid_identity);CHECK(cache.register_exact(u"chr/c0000/tex/body_s",0,0x201u)==runtime::spec_rgb_resource_result::fail_open_invalid_resource);CHECK(cache.register_exact(u"chr/c0000/tex/body_s",0x101u,0x201u)==runtime::spec_rgb_resource_result::registered);CHECK(cache.size()==1u);auto request=ready_request();auto plan=cache.plan_bind(request);CHECK(plan.activate);CHECK(plan.preserved_t1_srv==0x101u);CHECK(plan.ptde_t10_srv==0x201u);
cache.erase_companion(0x201u);CHECK(cache.size()==0u);plan=cache.plan_bind(request);CHECK(!plan.activate);CHECK(plan.ptde_t10_srv==0u);CHECK(cache.register_exact(u"chr/c0000/tex/body_s",0x101u,0x202u)==runtime::spec_rgb_resource_result::registered);plan=cache.plan_bind(request);CHECK(plan.activate);CHECK(plan.ptde_t10_srv==0x202u);
cache.clear();CHECK(cache.register_exact(u"a",0x301u,0x401u)==runtime::spec_rgb_resource_result::registered);CHECK(cache.register_exact(u"b",0x301u,0x402u)==runtime::spec_rgb_resource_result::fail_open_conflicting_stock_binding);runtime::spec_rgb_bind_request conflict=ready_request();conflict.logical_name=u"a";conflict.currently_bound_t1=0x301u;plan=cache.plan_bind(conflict);CHECK(!plan.activate);CHECK(cache.register_exact(u"c",0x301u,0x403u)==runtime::spec_rgb_resource_result::fail_open_conflicting_stock_binding);cache.erase_stock(0x301u);CHECK(cache.register_exact(u"c",0x301u,0x403u)==runtime::spec_rgb_resource_result::registered);CHECK(cache.register_exact(u"d",0x302u,0x403u)==runtime::spec_rgb_resource_result::fail_open_conflicting_companion);
std::cout<<"dsrrl_spec_rgb_resource_cache_tests: PASS\n";return 0;}
