#include "a3_ul_rx.hpp"

typedef unsigned char u8; typedef unsigned short u16; typedef unsigned int u32; typedef unsigned long long u64; typedef long long i64; typedef unsigned long long usize; typedef long HRESULT;
extern "C" void *memset(void *d,int c,usize n){volatile u8*p=(volatile u8*)d;for(usize i=0;i<n;++i)p[i]=(u8)c;return d;}
extern "C" void *memcpy(void *d,const void *s,usize n){volatile u8*dd=(volatile u8*)d;const volatile u8*ss=(const volatile u8*)s;for(usize i=0;i<n;++i)dd[i]=ss[i];return d;}
extern "C" int _fltused=0;
#define A3_EXPORT extern "C" __declspec(dllexport)
#define A3_NOINLINE __declspec(noinline)

struct GUID { u32 Data1; u16 Data2; u16 Data3; u8 Data4[8]; };
static const GUID IID_CTX1={0xbb2c6faau,0xb5fbu,0x4082u,{0x8e,0x6b,0x38,0x8b,0x8c,0xfa,0x90,0xe1}};
struct BufferDesc { u32 ByteWidth,Usage,BindFlags,CPUAccessFlags,MiscFlags,StructureByteStride; };

static inline void memzero(void*vp,usize n){volatile u8*p=(volatile u8*)vp;for(usize i=0;i<n;++i)p[i]=0;}
static inline void memcopy(void*vd,const void*vs,usize n){volatile u8*d=(volatile u8*)vd;const volatile u8*s=(const volatile u8*)vs;for(usize i=0;i<n;++i)d[i]=s[i];}
static inline bool memeql(const void*a,const void*b,usize n){const u8*x=(const u8*)a,*y=(const u8*)b;for(usize i=0;i<n;++i)if(x[i]!=y[i])return false;return true;}
static inline u16 rd16(const void*p){const u8*x=(const u8*)p;return (u16)(x[0]|((u16)x[1]<<8));}
static inline u32 rd32(const void*p){const u8*x=(const u8*)p;return (u32)x[0]|((u32)x[1]<<8)|((u32)x[2]<<16)|((u32)x[3]<<24);}
static inline void* vfn(void*o,u32 i){return o?(*(void***)o)[i]:0;}
static inline void addref(void*o){if(o)((u32(__fastcall*)(void*))vfn(o,1))(o);} static inline void release(void*o){if(o)((u32(__fastcall*)(void*))vfn(o,2))(o);}

static const u64 EXE_WRAPPER5=0x1C0BE0ull,EXE_WRAPPER6=0x1C0C10ull,EXE_BLEND=0x5642F0ull,EXE_SINGLE=0x564510ull,EXE_SELECTOR=0x22BA20ull;
static const u64 RET_SINGLE_U=0x563642ull,RET_SINGLE_L=0x563659ull,RET_BLEND_U=0x5639BAull,RET_BLEND_L=0x5639D5ull,RET_SEL1=0x20E019ull,RET_SEL2=0x20EB7Full,RET_SEL3=0x20FB9Eull;
static const u64 RVA_LEGACY_INIT=0x1b8e50ull,RVA_LEGACY_UNINIT=0x1b91f0ull,RVA_LEGACY_GATE=0x19c0e1ull,RVA_LEGACY_PRE=0x19c068ull;
static const u64 RVA_IAT_GETTID=0x0e008ull,RVA_IAT_GETMODULE=0x0e0f0ull,RVA_IAT_VFREE=0x0e108ull,RVA_IAT_VPROTECT=0x0e110ull,RVA_IAT_VALLOC=0x0e118ull,RVA_IAT_FLUSH=0x0e120ull,RVA_IAT_GETPROCESS=0x0e128ull;
static const u32 MEM_COMMIT_RESERVE=0x3000u,MEM_RELEASE=0x8000u,PAGE_RW=0x04u,PAGE_RWX=0x40u;

extern "C" void* g_a3_addon_base=0;
static inline void**iat(void*base,u64 rva){return (void**)((u8*)base+rva);}
static u32 GetTid(){void*b=g_a3_addon_base;return b?((u32(__stdcall*)())(*iat(b,RVA_IAT_GETTID)))():0;}
static void* GetModule(const wchar_t*n){void*b=g_a3_addon_base;return b?((void*(__stdcall*)(const wchar_t*))(*iat(b,RVA_IAT_GETMODULE)))(n):0;}
static void* VAlloc(void*a,usize n,u32 t,u32 p){void*b=g_a3_addon_base;return b?((void*(__stdcall*)(void*,usize,u32,u32))(*iat(b,RVA_IAT_VALLOC)))(a,n,t,p):0;}
static int VFree(void*a,usize n,u32 t){void*b=g_a3_addon_base;return b?((int(__stdcall*)(void*,usize,u32))(*iat(b,RVA_IAT_VFREE)))(a,n,t):0;}
static int VProtect(void*a,usize n,u32 p,u32*o){void*b=g_a3_addon_base;return b?((int(__stdcall*)(void*,usize,u32,u32*))(*iat(b,RVA_IAT_VPROTECT)))(a,n,p,o):0;}
static int Flush(void*p,usize n){void*b=g_a3_addon_base;if(!b)return 0;void*h=((void*(__stdcall*)())(*iat(b,RVA_IAT_GETPROCESS)))();return ((int(__stdcall*)(void*,const void*,usize))(*iat(b,RVA_IAT_FLUSH)))(h,p,n);}
static int VProtectFrom(void*base,void*a,usize n,u32 p,u32*o){return base?((int(__stdcall*)(void*,usize,u32,u32*))(*iat(base,RVA_IAT_VPROTECT)))(a,n,p,o):0;}

struct RawRGBM{i64 v;}; struct F4{float x,y,z,w;};
static RawRGBM read_rgbm(const void*p){RawRGBM r{};if(p)memcopy(&r,p,8);return r;} static F4 decode(RawRGBM q){short v[4];memcopy(v,&q,8);float s=(float)v[3]/100.0f;F4 o={(float)v[0]/255.0f*s,(float)v[1]/255.0f*s,(float)v[2]/255.0f*s,0};return o;} static F4 lerp4(F4 a,F4 b,float t){F4 o={a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t,0};return o;}

struct Snapshot{u64 owner;u16 a,b;u32 beta;F4 upper,lower;};
struct ThreadState{volatile u32 tid;int receiver;u32 snap_ready;Snapshot snap;u32 prod_active;u64 prod_owner;const u8*assignment;u32 have_u,have_l;F4 pu,pl;void*pre_ps;void*b13;void*b13_device;u32 draw_active;void*old_ps;void*old_b13;void*old_win;u32 old_first,old_num;void*ctx1;u32 explicit_window;};
struct Hook{void*target;void*tramp;u32 stolen;u8 original[32];};
struct State{volatile u32 snap_lock;volatile u32 shader_lock;u32 data_old_protect;void*addon;void*reshade;void*exe;void*log;u32 enabled;u32 first_active;u64 snapshots,selector_match,draw_pass,failopen,restore_fail;Snapshot snaps[512];ThreadState threads[64];void*device;void*stock_ps[47];void*alt_ps[47];Hook hooks[5];};

extern "C" void* g_a3_selector_trampoline=0; static State*g=0;
static void lock(volatile u32*l){while(__atomic_exchange_n(l,1u,__ATOMIC_ACQUIRE)){__builtin_ia32_pause();}} static void unlock(volatile u32*l){__atomic_store_n(l,0u,__ATOMIC_RELEASE);}
static ThreadState*ts(){if(!g)return 0;u32 id=GetTid();for(u32 i=0;i<64;++i){u32 cur=__atomic_load_n(&g->threads[i].tid,__ATOMIC_ACQUIRE);if(cur==id)return &g->threads[i];if(cur==0){u32 e=0;if(__atomic_compare_exchange_n(&g->threads[i].tid,&e,id,false,__ATOMIC_ACQ_REL,__ATOMIC_RELAXED)){g->threads[i].receiver=-1;return &g->threads[i];}}}return 0;}
static void logmsg(const char*s){if(g&&g->log)((void(__cdecl*)(void*,int,const char*))g->log)(g->addon,3,s);}
static void* find_export(void*module,const char*w){if(!module||!w)return 0;u8*b=(u8*)module;if(rd16(b)!=0x5a4d)return 0;u32 lf=rd32(b+0x3c);if(rd32(b+lf)!=0x4550)return 0;u8*opt=b+lf+24;if(rd16(opt)!=0x20b)return 0;u32 er=rd32(opt+112),es=rd32(opt+116);if(!er||!es)return 0;u8*e=b+er;u32 nn=rd32(e+24),fs=rd32(e+28),ns=rd32(e+32),os=rd32(e+36);for(u32 i=0;i<nn;++i){const char*n=(const char*)(b+rd32(b+ns+4*i));const char*a=n,*c=w;while(*a&&*c&&*a==*c){++a;++c;}if(*a||*c)continue;u16 ord=rd16(b+os+2*i);u32 r=rd32(b+fs+4*ord);if(r>=er&&r<er+es)return 0;return b+r;}return 0;}

static Snapshot*find_snap(u64 owner,bool create){u32 h=(u32)((owner>>4)^(owner>>23))&511u;for(u32 k=0;k<512;++k){Snapshot*s=&g->snaps[(h+k)&511u];if(s->owner==owner)return s;if(!s->owner&&create){s->owner=owner;return s;}}return 0;}
static void publish(ThreadState*t){if(!t||!t->prod_active||!t->prod_owner||!t->assignment||!t->have_u||!t->have_l)return;u16 a=rd16(t->assignment+8),b=rd16(t->assignment+10);u32 beta=rd32(t->assignment+12);lock(&g->snap_lock);Snapshot*s=find_snap(t->prod_owner,true);if(s){s->a=a;s->b=b;s->beta=beta;s->upper=t->pu;s->lower=t->pl;g->snapshots++;}unlock(&g->snap_lock);}

typedef void*(__fastcall*WrapFn)(void*,void*,void*,float);typedef void*(__fastcall*SingleFn)(void*,const void*,float);typedef void*(__fastcall*BlendFn)(void*,const void*,const void*,float);static WrapFn owrap5=0,owrap6=0;static SingleFn osingle=0;static BlendFn oblend=0;
static void*run_wrap(WrapFn fn,void*a,void*owner,void*assignment,float x){ThreadState*t=ts();if(!t)return fn(a,owner,assignment,x);u32 pa=t->prod_active;u64 po=t->prod_owner;const u8*pas=t->assignment;u32 hu=t->have_u,hl=t->have_l;F4 pu=t->pu,pl=t->pl;t->prod_active=1;t->prod_owner=(u64)owner;t->assignment=(const u8*)assignment;t->have_u=t->have_l=0;void*r=fn(a,owner,assignment,x);publish(t);t->prod_active=pa;t->prod_owner=po;t->assignment=pas;t->have_u=hu;t->have_l=hl;t->pu=pu;t->pl=pl;return r;}
extern "C" void* __fastcall a3_hook_wrap5(void*a,void*o,void*as,float x){return run_wrap(owrap5,a,o,as,x);}extern "C" void* __fastcall a3_hook_wrap6(void*a,void*o,void*as,float x){return run_wrap(owrap6,a,o,as,x);}
extern "C" void* __fastcall a3_hook_single(void*dst,const void*v,float w){ThreadState*t=ts();if(t&&t->prod_active&&v){F4 q=decode(read_rgbm(v));u64 r=(u64)__builtin_return_address(0)-(u64)g->exe;if(r==RET_SINGLE_U){t->pu=q;t->have_u=1;}else if(r==RET_SINGLE_L){t->pl=q;t->have_l=1;}}return osingle(dst,v,w);}extern "C" void* __fastcall a3_hook_blend(void*dst,const void*a,const void*b,float beta){ThreadState*t=ts();if(t&&t->prod_active&&a&&b){F4 q=lerp4(decode(read_rgbm(a)),decode(read_rgbm(b)),beta);u64 r=(u64)__builtin_return_address(0)-(u64)g->exe;if(r==RET_BLEND_U){t->pu=q;t->have_u=1;}else if(r==RET_BLEND_L){t->pl=q;t->have_l=1;}}return oblend(dst,a,b,beta);}

static bool write_jump(void*at,void*to,u32 span){if(!at||!to||span<14||span>32)return false;u8 p[32];for(u32 i=0;i<span;++i)p[i]=0x90;p[0]=0xff;p[1]=0x25;u64 q=(u64)to;memcopy(p+6,&q,8);u32 old=0;if(!VProtect(at,span,PAGE_RWX,&old))return false;memcopy(at,p,span);Flush(at,span);u32 dummy=0;VProtect(at,span,old,&dummy);return true;}
static bool install(Hook*h,u64 rva,const u8*exp,u32 n,void*detour){u8*t=(u8*)g->exe+rva;if(!memeql(t,exp,n))return false;void*tr=VAlloc(0,n+14,MEM_COMMIT_RESERVE,PAGE_RWX);if(!tr)return false;memcopy(tr,t,n);u8*e=(u8*)tr+n;e[0]=0xff;e[1]=0x25;for(int i=2;i<6;++i)e[i]=0;u64 back=(u64)(t+n);memcopy(e+6,&back,8);h->target=t;h->tramp=tr;h->stolen=n;memcopy(h->original,t,n);if(!write_jump(t,detour,n)){VFree(tr,0,MEM_RELEASE);memzero(h,sizeof(*h));return false;}return true;}
static void restore_hooks(){if(!g)return;for(u32 i=0;i<5;++i){Hook*h=&g->hooks[i];if(!h->target)continue;u32 old=0;if(VProtect(h->target,h->stolen,PAGE_RWX,&old)){memcopy(h->target,h->original,h->stolen);Flush(h->target,h->stolen);u32 d=0;VProtect(h->target,h->stolen,old,&d);}if(h->tramp)VFree(h->tramp,0,MEM_RELEASE);memzero(h,sizeof(*h));}g_a3_selector_trampoline=0;}
extern "C" void a3_selector_observer(void*owner,void*ret,void*r14,void*r15){ThreadState*t=ts();if(!t)return;u64 rr=(u64)ret-(u64)g->exe;const u8*desc=0;if(rr==RET_SEL1||rr==RET_SEL3)desc=(const u8*)r15;else if(rr==RET_SEL2)desc=(const u8*)r14;else{t->snap_ready=0;return;}if(!owner||!desc){t->snap_ready=0;return;}u16 a=rd16(desc+0x4c),b=rd16(desc+0x4e);u32 beta=rd32(desc+0x50);lock(&g->snap_lock);Snapshot*s=find_snap((u64)owner,false);if(s&&s->a==a&&s->b==b&&s->beta==beta){t->snap=*s;t->snap_ready=1;g->selector_match++;}else t->snap_ready=0;unlock(&g->snap_lock);}
extern "C" void a3_selector_hook_entry();
static bool install_producer(){static const u8 bw[17]={0x48,0x83,0xec,0x38,0x4d,0x8b,0xc8,0xf3,0x0f,0x11,0x5c,0x24,0x20,0x4c,0x8b,0x41,0x40};static const u8 bb[19]={0x48,0x8b,0xc4,0x48,0x89,0x58,0x08,0x48,0x89,0x70,0x10,0x57,0x48,0x81,0xec,0xc0,0x00,0x00,0x00};static const u8 bs[14]={0x48,0x89,0x5c,0x24,0x08,0x57,0x48,0x83,0xec,0x40,0x0f,0xbf,0x42,0x06};static const u8 bsel[15]={0x40,0x53,0x48,0x83,0xec,0x30,0x49,0x63,0xc0,0x45,0x8b,0xd1,0x48,0x8b,0xda};if(!install(&g->hooks[0],EXE_WRAPPER5,bw,17,(void*)&a3_hook_wrap5))return false;owrap5=(WrapFn)g->hooks[0].tramp;if(!install(&g->hooks[1],EXE_WRAPPER6,bw,17,(void*)&a3_hook_wrap6))return false;owrap6=(WrapFn)g->hooks[1].tramp;if(!install(&g->hooks[2],EXE_BLEND,bb,19,(void*)&a3_hook_blend))return false;oblend=(BlendFn)g->hooks[2].tramp;if(!install(&g->hooks[3],EXE_SINGLE,bs,14,(void*)&a3_hook_single))return false;osingle=(SingleFn)g->hooks[3].tramp;if(!install(&g->hooks[4],EXE_SELECTOR,bsel,15,(void*)&a3_selector_hook_entry))return false;g_a3_selector_trampoline=g->hooks[4].tramp;return true;}

static void release_shader_cache(){if(!g)return;for(u32 i=0;i<47;++i){release(g->stock_ps[i]);g->stock_ps[i]=0;release(g->alt_ps[i]);g->alt_ps[i]=0;}release(g->device);g->device=0;}
static void* get_ul_ps(void*dev,u32 rx,bool alt){if(!g||rx>=47)return 0;lock(&g->shader_lock);if(g->device!=dev){release_shader_cache();g->device=dev;addref(dev);}void**slot=alt?&g->alt_ps[rx]:&g->stock_ps[rx];const A3ULRxRec&r=a3_ul_rx_recs[rx];u32 off=alt?r.alt_off:r.stock_off,sz=alt?r.alt_size:r.stock_size;if(!sz){unlock(&g->shader_lock);return 0;}if(!*slot){void*p=0;typedef HRESULT(__fastcall*Fn)(void*,const void*,usize,void*,void**);HRESULT hr=((Fn)vfn(dev,15))(dev,a3_ul_rx_blob+off,sz,0,&p);if(hr<0||!p){unlock(&g->shader_lock);return 0;}*slot=p;}void*out=*slot;addref(out);unlock(&g->shader_lock);return out;}
static void* get_device(void*ctx){void*d=0;if(ctx)((void(__fastcall*)(void*,void**))vfn(ctx,3))(ctx,&d);return d;}
static void ps_get(void*ctx,void**out){if(out)*out=0;if(ctx)((void(__fastcall*)(void*,void**,void**,u32*))vfn(ctx,74))(ctx,out,0,0);} static void ps_set(void*ctx,void*ps){((void(__fastcall*)(void*,void*,void*,u32))vfn(ctx,9))(ctx,ps,0,0);} static void cb_get(void*ctx,u32 slot,void**out){if(out)*out=0;((void(__fastcall*)(void*,u32,u32,void**))vfn(ctx,77))(ctx,slot,1,out);} static void cb_set(void*ctx,u32 slot,void*b){void*x=b;((void(__fastcall*)(void*,u32,u32,void**))vfn(ctx,16))(ctx,slot,1,&x);} 
static void* query_ctx1(void*ctx){void*x=0;if(!ctx)return 0;HRESULT hr=((HRESULT(__fastcall*)(void*,const GUID*,void**))vfn(ctx,0))(ctx,&IID_CTX1,&x);return hr<0?0:x;}
static void cb1_get(void*c,u32 slot,void**b,u32*f,u32*n){((void(__fastcall*)(void*,u32,u32,void**,u32*,u32*))vfn(c,129))(c,slot,1,b,f,n);} static void cb1_set(void*c,u32 slot,void*b,u32 f,u32 n){void*x=b;((void(__fastcall*)(void*,u32,u32,void**,const u32*,const u32*))vfn(c,123))(c,slot,1,&x,&f,&n);} 
static void update_resource(void*ctx,void*res,const void*data){((void(__fastcall*)(void*,void*,u32,const void*,const void*,u32,u32))vfn(ctx,48))(ctx,res,0,0,data,0,0);} static void* make_b13(void*dev){BufferDesc bd{128,0,4,0,0,0};void*b=0;HRESULT hr=((HRESULT(__fastcall*)(void*,const BufferDesc*,const void*,void**))vfn(dev,3))(dev,&bd,0,&b);return hr<0?0:b;}
static void clear_pre(ThreadState*t){if(t&&t->pre_ps){release(t->pre_ps);t->pre_ps=0;}}
extern "C" void a3_capture_receiver(u64 stride){ThreadState*t=ts();if(!t||!g||!g->enabled)return;t->receiver=(stride%0x38ull)==0?(int)(stride/0x38ull):-1;if(t->receiver<0||t->receiver>50)t->receiver=-1;}
extern "C" void a3_capture_pre_ps(void*ctx){ThreadState*t=ts();if(!t||!g||!g->enabled)return;clear_pre(t);ps_get(ctx,&t->pre_ps);}
extern "C" void a3_prepare_draw(void*ctx){ThreadState*t=ts();if(!t||!g||!g->enabled){if(t)t->snap_ready=0;return;}t->draw_active=0;if(!t->snap_ready||t->receiver<0||t->receiver>=47||!t->pre_ps){g->failopen++;t->snap_ready=0;clear_pre(t);return;}void*cur=0;ps_get(ctx,&cur);if(!cur){g->failopen++;t->snap_ready=0;clear_pre(t);return;}bool alt=cur!=t->pre_ps;const A3ULRxRec&r=a3_ul_rx_recs[t->receiver];if(alt&&!r.alt_size){release(cur);g->failopen++;t->snap_ready=0;clear_pre(t);return;}void*dev=get_device(ctx);if(!dev){release(cur);g->failopen++;t->snap_ready=0;clear_pre(t);return;}void*ulps=get_ul_ps(dev,(u32)t->receiver,alt);if(!ulps){release(dev);release(cur);g->failopen++;t->snap_ready=0;clear_pre(t);return;}if(t->b13_device!=dev){release(t->b13);t->b13=0;release(t->b13_device);t->b13_device=dev;addref(dev);}if(!t->b13)t->b13=make_b13(dev);release(dev);if(!t->b13){release(ulps);release(cur);g->failopen++;t->snap_ready=0;clear_pre(t);return;}F4 payload[8];memzero(payload,sizeof(payload));payload[6]=t->snap.upper;payload[7]=t->snap.lower;update_resource(ctx,t->b13,payload);t->old_ps=cur;t->ctx1=query_ctx1(ctx);cb_get(ctx,13,&t->old_b13);t->old_win=0;t->old_first=t->old_num=0;t->explicit_window=0;if(t->ctx1){cb1_get(t->ctx1,13,&t->old_win,&t->old_first,&t->old_num);if(t->old_b13!=t->old_win){release(t->old_b13);t->old_b13=0;release(t->old_win);t->old_win=0;release(t->ctx1);t->ctx1=0;release(ulps);g->failopen++;t->snap_ready=0;clear_pre(t);release(cur);t->old_ps=0;return;}if(t->old_win&&t->old_num>=16&&(t->old_first%16)==0&&(t->old_num%16)==0)t->explicit_window=1;}ps_set(ctx,ulps);cb_set(ctx,13,t->b13);release(ulps);t->draw_active=1;g->draw_pass++;if(!g->first_active){g->first_active=1;logmsg("DSRRL A3 U/L: FIRST PTDE U/L DRAW ACTIVE");}}
extern "C" void a3_finish_draw(void*ctx){ThreadState*t=ts();if(!t)return;if(t->draw_active){if(t->ctx1&&t->explicit_window)cb1_set(t->ctx1,13,t->old_win,t->old_first,t->old_num);else cb_set(ctx,13,t->old_b13);ps_set(ctx,t->old_ps);void*chk=0;cb_get(ctx,13,&chk);bool ok=chk==t->old_b13;release(chk);if(t->ctx1){void*w=0;u32 f=0,n=0;cb1_get(t->ctx1,13,&w,&f,&n);ok=ok&&w==t->old_win&&(!t->explicit_window||(f==t->old_first&&n==t->old_num));release(w);}if(!ok){g->restore_fail++;g->enabled=0;logmsg("DSRRL A3 U/L: RESTORE FAILURE, U/L quarantined");}}release(t->old_ps);t->old_ps=0;release(t->old_b13);t->old_b13=0;release(t->old_win);t->old_win=0;release(t->ctx1);t->ctx1=0;t->draw_active=0;t->snap_ready=0;clear_pre(t);t->receiver=-1;}

static bool protect_a3_data_page(void*addon,u32*old_out){u64 a=(u64)&g_a3_selector_trampoline,b=(u64)&g;u64 lo=(a<b?a:b)&~0xfffull;u64 hi=((a>b?a:b)+sizeof(void*)+0xfffull)&~0xfffull;u32 old=0;if(!VProtectFrom(addon,(void*)lo,(usize)(hi-lo),PAGE_RW,&old))return false;if(old_out)*old_out=old;return true;}
static void restore_a3_data_page(void*addon,u32 old){u64 a=(u64)&g_a3_selector_trampoline,b=(u64)&g;u64 lo=(a<b?a:b)&~0xfffull;u64 hi=((a>b?a:b)+sizeof(void*)+0xfffull)&~0xfffull;u32 dummy=0;VProtectFrom(addon,(void*)lo,(usize)(hi-lo),old,&dummy);}
static bool init_a3(void*addon,void*reshade){u32 data_old=0;if(!protect_a3_data_page(addon,&data_old))return false;g_a3_addon_base=addon;void*mem=VAlloc(0,sizeof(State),MEM_COMMIT_RESERVE,PAGE_RW);if(!mem){g_a3_addon_base=0;restore_a3_data_page(addon,data_old);return false;}g=(State*)mem;memzero(g,sizeof(State));g->data_old_protect=data_old;g->addon=addon;g->reshade=reshade;g->exe=GetModule(0);g->log=find_export(reshade,"ReShadeLogMessage");if(!g->exe){VFree(g,0,MEM_RELEASE);g=0;return false;}if(!install_producer()){logmsg("DSRRL A3 U/L: producer/selector preflight failed; U/L fail-open");restore_hooks();g->enabled=0;return true;}g->enabled=1;logmsg("DSRRL A3 monolith: PTDE U/L producer armed; EnvDiffuse resource bridge OFF");return true;}
static void shutdown_a3(){if(!g)return;g->enabled=0;restore_hooks();release_shader_cache();for(u32 i=0;i<64;++i){ThreadState*t=&g->threads[i];release(t->pre_ps);release(t->b13);release(t->b13_device);release(t->old_ps);release(t->old_b13);release(t->old_win);release(t->ctx1);}u32 data_old=g->data_old_protect;void*addon=g->addon;State*old=g;g=0;VFree(old,0,MEM_RELEASE);g_a3_addon_base=0;restore_a3_data_page(addon,data_old);}

extern "C" u8 a3_call_legacy_gate(void*rcx,u64 rdx){void*b=g_a3_addon_base;if(!b)return 0;return ((u8(__fastcall*)(void*,u64))((u8*)b+RVA_LEGACY_GATE))(rcx,rdx);}
extern "C" void a3_call_legacy_pre(){void*b=g_a3_addon_base;if(b)((void(__fastcall*)())((u8*)b+RVA_LEGACY_PRE))();}
A3_EXPORT bool a3_init_wrapper(void*addon,void*reshade){bool ok=((bool(__fastcall*)(void*,void*))((u8*)addon+RVA_LEGACY_INIT))(addon,reshade);if(!ok)return false;init_a3(addon,reshade);return true;}A3_EXPORT void a3_uninit_wrapper(void*addon,void*reshade){shutdown_a3();((void(__fastcall*)(void*,void*))((u8*)addon+RVA_LEGACY_UNINIT))(addon,reshade);} 